_prefs:
  saveCenter: false
_properties:
  bridge:
    "group-by": layer
attribution: "<a href=\"#\">Justin Palmer</a>, <a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds:
  - -180
  - -85.0511
  - 180
  - 85.0511
center:
  - -122.6836
  - 45.5253
  - 14
description: 2014 restaurant inspections in Portland, OR.
format: "png8:m=h"
interactivity_layer: ''
layers:
  - landcover
  - hillshade
  - contour
  - landuse
  - waterway
  - water
  - aeroway
  - barrier_line
  - building
  - landuse_overlay
  - tunnel
  - road
  - bridge
  - buildings
  - admin
  - parks
  - neighborhoods
  - crashes
  - inspections
  - country_label_line
  - country_label
  - marine_label
  - state_label
  - place_label
  - water_label
  - poi_label
  - road_label
  - waterway_label
  - housenum_label
maxzoom: 22
minzoom: 14
name: Portland Restaurant Inspections
source: "mapbox:///mapbox.mapbox-terrain-v1,mapbox.mapbox-streets-v5,caged.845d6d73"
styles:
  - style.mss
  - labels.mss
  - roads.mss
  - buildings.mss
  - inspections.mss
template: ''
